#!/bin/env sh

compileOpen() {
	echo Compiling openSpotifyHack
	tsc --pretty ./injectionScripts/openSpotifyHack.ts --outDir ~/dev/extensions/browser/MyExtension/dist/
}

compileClient() {
	echo Compiling SpotifyHack
	tsc --pretty ./injectionScripts/spotifyHack.ts --outDir ~/.config/spicetify/Extensions/ &&
		spicetify apply &&
		pkill spotify
}

case "$1" in
	"open" | "openSpotifyHack.ts") compileOpen ;;

	"spotify" | "spotifyHack.ts") compileClient ;;

	*)
		echo Compiling Both
		compileOpen
		compileClient
		;;

esac
