#!/bin/env sh

compileOpen() {
	echo Compiling openSpotifyHack
	tsc --pretty ./injectionScripts/openSpotifyHack.ts --outDir ~/dev/extensions/browser/MyExtension/dist/
}

compileClient() {
	echo Compiling SpotifyHack
	tsc --pretty ./injectionScripts/spotifyHack.ts --outDir ~/.config/spicetify/Extensions/ &&
		spicetify apply &&
		pkill spotify
}

case "$1" in
	"o" | "open" | "openSpotifyHack.ts" | "./injectionScripts/openSpotifyHack.ts" | "injectionScripts/openSpotifyHack.ts" ) compileOpen ;;

	"s" | "spotify" | "spotifyHack.ts" | "./injectionScripts/spotifyHack.ts" | "injectionScripts/spotifyHack.ts" ) compileClient ;;

	*)
		echo Compiling Both
		compileOpen
		compileClient
		;;

esac
